In [1]:
import numpy as np

In [2]:
a = np.array ([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
import time

In [6]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("Vectorized Version:" + str(1000*(toc-tic)) + "ms")

#much quicker

Vectorized Version:26.958227157592773ms


In [7]:
c = 0
tic = time.time()
for i in range (1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("For loop:" + str(1000*(toc-tic)) + "ms")

249903.23380749376
For loop:874.1638660430908ms


Whenever possible avoid explicit for-loops.
Vectorizatin of u = Av

u = np.dot(A, v)


Broadcasting operation demo in python. calculating percentages for each column of the matrix
If you have an (m,n) matrix and you add or subtract or multiply or divide with a (1,n) matrix, then this will copy it n times into an (m,n) matrix. And then apply the addition, subtraction, and multiplication of division element wise.

If conversely, you were to take the (m,n) matrix and add, subtract, multiply, divide by an (m,1) matrix, then also this would copy it now n times. And turn that into an (m,n) matrix and then apply the operation element wise.

In [9]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2, 104.0, 52.0, 8.0],
            [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [10]:
sum_col = A.sum(axis=0) #sum vertically, axis=1, is horizontally
print(sum_col)

[ 59.  239.  155.4  76.9]


In [12]:
percentage = 100 * A/sum_col.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [13]:
#same as above
perc = 100 * A/sum_col
print(perc)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [15]:
##did not work. assert(perc.shape == (3,3))


AssertionError: 